// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjlsjdxboijvejugtqyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbHNqZHhib2lqdmVqdWd0cXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDc4MTksImV4cCI6MjA2NDAyMzgxOX0.NfN6De1RAug33X2p4LESWDiHHjEVEX16V5GMo_YyP-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);